apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
