"""rework appointment slot linkage

Revision ID: 8524b9522086
Revises: f37a2b7a28f8
Create Date: 2026-07-24 22:32:52.157191

Drops the UNIQUE on appointments.slot_id and adds a nullable
workflow_run_id plus a partial unique index over it.

The unique slot_id was never the concurrency guard - the conditional
`UPDATE appointment_slots SET status='booked' WHERE status='free'` in
book_appointment is - but it did permanently kill any slot that was ever
cancelled, because cancelling frees the slot and leaves the old
appointment row pointing at it. slot_id keeps a plain index instead.

The partial unique index puts the one-booking-per-workflow-run rule in
the database: a replayed or retried run cannot produce a second confirmed
appointment. Cancelled rows fall outside the predicate, so a run can
rebook after a cancellation.

SQLite cannot drop a column-level UNIQUE (it lives in an auto-index), so
that branch recreates the table in batch mode from a copy_from that
simply omits the constraint.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8524b9522086'
down_revision: Union[str, Sequence[str], None] = 'f37a2b7a28f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PARTIAL = "workflow_run_id IS NOT NULL AND status = 'confirmed'"

# Postgres named the initial-schema UNIQUE for us. The default is
# appointments_slot_id_key, but the name is autogenerated, so look it up
# rather than trust it.
_PG_SLOT_UNIQUE_FALLBACK = "appointments_slot_id_key"

# Batch mode refuses to add an unnamed constraint, so the new foreign key
# carries an explicit name.
_FK_WORKFLOW_RUN = "fk_appointments_workflow_run_id"


def _appointments_before() -> sa.Table:
    """The appointments table as the initial schema left it, minus the
    UNIQUE on slot_id: batch mode rebuilds the table from this."""
    return sa.Table(
        "appointments",
        sa.MetaData(),
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("patient_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("doctor_id", sa.Integer, sa.ForeignKey("doctors.id"), nullable=False),
        sa.Column("slot_id", sa.Integer, sa.ForeignKey("appointment_slots.id"), nullable=False),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime, server_default=sa.func.now(), nullable=False),
    )


def _appointments_after() -> sa.Table:
    """The same table once this revision has run, for the downgrade
    rebuild. copy_from has to describe everything that is really there,
    indexes included, or batch mode cannot drop them."""
    table = _appointments_before()
    table.append_column(
        sa.Column(
            "workflow_run_id",
            sa.Integer,
            sa.ForeignKey("workflow_runs.id", name=_FK_WORKFLOW_RUN),
            nullable=True,
        )
    )
    sa.Index("ix_appointments_slot_id", table.c.slot_id)
    return table


def _slot_id_unique_name(bind) -> str:
    for constraint in sa.inspect(bind).get_unique_constraints("appointments"):
        if constraint["column_names"] == ["slot_id"]:
            return constraint["name"]
    return _PG_SLOT_UNIQUE_FALLBACK


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.drop_constraint(_slot_id_unique_name(bind), "appointments", type_="unique")
        op.add_column(
            "appointments",
            sa.Column(
                "workflow_run_id", sa.Integer, sa.ForeignKey("workflow_runs.id"), nullable=True
            ),
        )
        op.create_index("ix_appointments_slot_id", "appointments", ["slot_id"])
        op.create_index(
            "uq_appointments_workflow_run",
            "appointments",
            ["workflow_run_id"],
            unique=True,
            postgresql_where=sa.text(_PARTIAL),
        )
    else:
        with op.batch_alter_table("appointments", copy_from=_appointments_before()) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "workflow_run_id",
                    sa.Integer,
                    sa.ForeignKey("workflow_runs.id", name=_FK_WORKFLOW_RUN),
                    nullable=True,
                )
            )
            batch_op.create_index("ix_appointments_slot_id", ["slot_id"])
        op.create_index(
            "uq_appointments_workflow_run",
            "appointments",
            ["workflow_run_id"],
            unique=True,
            sqlite_where=sa.text(_PARTIAL),
        )


def downgrade() -> None:
    """Downgrade schema.

    Fails if any slot carries more than one appointment row, which is
    exactly the state this revision made legal. Cancelled duplicates have
    to be cleared out by hand before downgrading.
    """
    bind = op.get_bind()
    op.drop_index("uq_appointments_workflow_run", table_name="appointments")
    if bind.dialect.name == "postgresql":
        op.drop_index("ix_appointments_slot_id", table_name="appointments")
        op.drop_column("appointments", "workflow_run_id")
        op.create_unique_constraint(_PG_SLOT_UNIQUE_FALLBACK, "appointments", ["slot_id"])
    else:
        # Named, unlike the original inline UNIQUE that sqlite left
        # anonymous; same effect, and batch mode requires a name.
        with op.batch_alter_table("appointments", copy_from=_appointments_after()) as batch_op:
            batch_op.drop_index("ix_appointments_slot_id")
            batch_op.drop_column("workflow_run_id")
            batch_op.create_unique_constraint("uq_appointments_slot_id", ["slot_id"])
