"""agent rules

Revision ID: f37a2b7a28f8
Revises: 64fa00aef454
Create Date: 2026-07-24 12:32:10.138427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37a2b7a28f8'
down_revision: Union[str, Sequence[str], None] = '64fa00aef454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('seed', 'staff', name='agent_rule_source'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_rules_agent_name'), ['agent_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_rules_agent_name'))

    op.drop_table('agent_rules')
    # ### end Alembic commands ###
